.TH OSRM-COMPONENTS 1 "July  4, 2013" osrm-components "Open Source Rouing Machine"
.SH NAME
osrm-components \- gives information about unroutable roads in the data
.SH SYNOPSIS
.B osrm-components
.I data.osrm
.I data.osrm.restrictions
.SH DESCRIPTION
Produces some statistics, and a shapefile (with associated data) regarding the input data.
.SH SEE ALSO
.BR osrm (7),
.BR osrm-extract (1),
.BR osrm-prepare (1),
.BR osrm-routed (1)
